docs: initial content for UI Styling in NativeScript
NativeScript/docs pull request #19
Opened 2022-11-19 21:45 UTC by Ombuweb

2023-07-31 23:12 UTC, SeanKelly369 commented on content/guide/ui/styling.md
> +In NativeScript you style the UI similarly to how you do it in a web application using Cascading Style Sheets (CSS), or by changing the style property of the views in JavaScript/Typescript. For CSS s
```suggestion
In NativeScript, UIs are styled similarly to how web applications using Cascading Style Sheets (CSS) are styled, or by changing the style property of the views in JavaScript/Typescript.  For CSS styling, NativeScript supports tools such as [Tailwind](https://docs.nativescript.org/plugins/tailwindcss.html), [SASS](#using-sass). 
```

2023-07-31 23:12 UTC, SeanKelly369 commented on content/guide/ui/styling.md
> +In NativeScript you style the UI similarly to how you do it in a web application using Cascading Style Sheets (CSS), or by changing the style property of the views in JavaScript/Typescript. For CSS s
It is worth pointing out that SCSS and SASS can be used in place of CSS.

2023-07-31 23:12 UTC, SeanKelly369 commented on content/guide/ui/styling.md
> +If there is CSS declared on different levels&mdash;all will be applied. The inline CSS will have the highest priority and the application CSS will have the lowest priority.
```suggestion
Like with web development, if there is CSS declared on different levels&mdash;all will be applied. The inline CSS will have the highest priority and the application CSS will have the lowest priority, with classes having a lower priority to IDs.  If multiple classes are called and they use the same properties, the last class called overwrites the previous property value.
```

2023-07-31 23:12 UTC, SeanKelly369 commented on content/guide/ui/styling.md
> +| `background`          | `background`          | Sets a solid-color value or [a linear gradient](https://docs.nativescript.org/cookbook/ui/styling) to the matched view’s background.
Broken link, as mentioned on line 206

2023-07-31 23:12 UTC, SeanKelly369 commented on content/guide/ui/styling.md
> +| `clip-path`           | `clip-path`           | Sets the clip-path. Supported shapes are circle, ellipse, rect and polygon. You can define your own shape using [clippy](http://bennettfeely.com/clip
Is it `clip-path`, or is it `clipPath`?

2023-07-31 23:12 UTC, SeanKelly369 commented on content/guide/ui/styling.md
> +| `clip-path`           | `clip-path`           | Sets the clip-path. Supported shapes are circle, ellipse, rect and polygon. You can define your own shape using [clippy](http://bennettfeely.com/clip
There is no need for the / at the end of the link.

2023-07-31 23:12 UTC, SeanKelly369 commented on content/guide/ui/styling.md
> +Currently, we can set only the `backgroundColor`, `color`, `fontFamily`, `fontSize`, `fontStyle`, `fontWeight` and `textTransform` styling properties to the `Label` and `Image` components inside the
Is this still the case?

2023-07-31 23:12 UTC, SeanKelly369 commented on content/guide/ui/styling.md
> +  <label androidElevation="5" class="sampleLabel" textWrap="true" text="Label"></label>
Are the tags for `label` and `button` right?  Do they need to start with an uppercase character, or is it entirely optional?

2023-07-31 23:12 UTC, SeanKelly369 commented on content/guide/ui/styling.md
> +NativeScript's recommended measurement unit is `DIP`. All measurable properties like width, height, margin, paddings, border-width, etc.) support `DIPs`. The font sizes are always measured in DIPs.
It is worth mentioning DIPs is the default measurement in general.

2023-08-03 02:15 UTC, ashutosh887 commented on content/guide/ui/styling.md
> +In NativeScript you style the UI similarly to how you do it in a web application using Cascading Style Sheets (CSS), or by changing the style property of the views in JavaScript/Typescript. For CSS s
```suggestion
In NativeScript you style the UI similarly to how you do it in a web application using Cascading Style Sheets (CSS), or by changing the style property of the views in JavaScript/Typescript. For CSS styling, NativeScript supports tools such as [Tailwind](https://docs.nativescript.org/plugins/tailwindcss.html), [SASS](#using-sass). 
```

In NativeScript, UIs are styled similarly to how web applications using Cascading Style Sheets (CSS) are styled or by changing the style property of the views in JavaScript/TypeScript. For CSS styling, NativeScript supports tools such as [Tailwind](https://docs.nativescript.org/plugins/tailwindcss.html) and [SASS](#using-sass).

2023-08-03 02:16 UTC, ashutosh887 commented on content/guide/ui/styling.md
> +In NativeScript you style the UI similarly to how you do it in a web application using Cascading Style Sheets (CSS), or by changing the style property of the views in JavaScript/Typescript. For CSS s
@NathanWalker

2023-08-03 02:19 UTC, ashutosh887 commented on content/guide/ui/styling.md
> +If there is CSS declared on different levels&mdash;all will be applied. The inline CSS will have the highest priority and the application CSS will have the lowest priority.
```suggestion
If there is CSS declared on different levels&mdash;all will be applied. The inline CSS will have the highest priority and the application CSS will have the lowest priority.
```

If CSS is declared at different levels, all styles will be applied. Inline CSS takes the highest priority, while application-level CSS has the lowest priority.

2023-08-03 02:21 UTC, ashutosh887 requested changes
@NathanWalker I've added some comments to replace the current textual content there!

2023-08-31 04:12 UTC, merged