docs: Core Color class WIP
NativeScript/docs pull request #41
Opened 2022-11-21 20:43 UTC by Ombuweb

2023-06-19 18:58 UTC, ashutosh887 requested changes

2023-06-19 18:58 UTC, ashutosh887 commented on content/guide/core/color.md
> +This class allows you to create a color object with all color components(alpha, red, green, blue in the [0, 255] range) from different types of color representations such as, ARGB, color name, hex, e
This class enables the creation of a color object with color components (alpha, red, green, blue) ranging from 0 to 255, using various color representations such as ARGB, color names, hex values, and more. The properties ios and android of an instance of this class provide the corresponding color object for the respective native platforms.

2023-06-19 18:58 UTC, ashutosh887 commented on content/guide/core/color.md
> +Gets the android-specific integer value representation. Same as the Argb one.
`ARGB` one

2023-07-28 15:11 UTC, NathanWalker commented on content/guide/core/color.md
> +This class allows you to create a color object with all color components(alpha, red, green, blue in the [0, 255] range) from different types of color representations such as, ARGB, color name, hex, e
```suggestion
This `Color` class enables the creation of a color object with color components (alpha, red, green, blue) ranging from 0 to 255, using various color representations such as ARGB, color names, hex values, and more. The properties `ios` and `android` of an instance of this class provide the corresponding color object for the respective native platforms such as [UIColor](https://developer.apple.com/documentation/uikit/uicolor) on iOS and [Color ints](https://developer.android.com/reference/android/graphics/Color) on Android.
```

2023-07-28 15:12 UTC, NathanWalker commented on content/guide/core/color.md
> +Gets the android-specific integer value representation. Same as the Argb one.
```suggestion
Gets the android-specific integer value representation. Same as the `ARGB` one.
```

2023-07-28 16:14 UTC, rigor789 commented on content/guide/core/color.md
> +This `Color` class enables the creation of a color object with color components (alpha, red, green, blue) ranging from 0 to 255, using various color representations such as ARGB, color names, hex val
```suggestion
The `Color` class enables the creation of a color object:
 - using color components (alpha, red, green, blue) ranging from 0 to 255,
 - using various color representations like ARGB, color names, hex values, and more.
 
The `ios` and `android` properties of the `Color` class instance return the native [UIColor](https://developer.apple.com/documentation/uikit/uicolor) on iOS and [Color](https://developer.android.com/reference/android/graphics/Color) on Android.
```

Note: `using various color representations like ARGB, color names, hex values, and more.` we should define `and more` or remove it.

Suggestion:
 - split each option as a new line/list item and link them within the page. ie -> color names should link to a section about using color names etc.

2023-08-13 20:04 UTC, merged