docs: initial commit
NativeScript/docs pull request #44
Opened 2022-11-23 15:38 UTC by Ombuweb

2023-06-19 18:46 UTC, ashutosh887 commented on content/guide/core/fps-meter.md
> +Adds a callback function to be called each time FPS data is ready. The a unique `number` id which can be used to remove this callback later.
Implement a callback function that will be executed whenever FPS data becomes available. Assign a unique numerical identifier (`number`) to this callback, facilitating its future removal, if required.

2023-06-19 18:48 UTC, ashutosh887 requested changes

2023-06-19 18:48 UTC, ashutosh887 commented on content/guide/core/fps-meter.md
> +Adds a callback function to be called each time FPS data is ready. The a unique `number` id which can be used to remove this callback later.
Implement a callback function that will be executed whenever FPS data becomes available. Assign a unique numerical identifier (`number`) to this callback, facilitating its future removal, if required.

2023-06-19 18:49 UTC, ashutosh887 commented
@NathanWalker I've requested some changes!

2023-07-28 15:02 UTC, NathanWalker commented on content/guide/core/fps-meter.md
> +Adds a callback function to be called each time FPS data is ready. The a unique `number` id which can be used to remove this callback later.
```suggestion
Implement a callback function that will be executed whenever FPS data becomes available. Assign a unique identifier (`number`) to this callback, facilitating its future removal, if needed.
```

2023-07-28 15:03 UTC, NathanWalker commented on content/guide/core/fps-meter.md
> +This module allows you capture the frames-per-second metrics of your application.
```suggestion
FPS Meter allows you capture the frames-per-second metrics of your application.
```

2023-07-28 15:03 UTC, NathanWalker commented on content/guide/core/fps-meter.md
> +### Measuring the fps
```suggestion
### Measuring FPS
```

2023-07-28 15:04 UTC, NathanWalker commented on content/guide/core/fps-meter.md
> +To use the module, first register a callback that will receive the FPS metrics using the [addCallBack](#addcallback) method. Then, call the [start](#start) method to start measuring the fps.
```suggestion
Register a callback that will receive the FPS metrics using the [addCallBack](#addcallback) method. Then call the [start](#start) method to begin measuring.
```

2023-07-28 15:04 UTC, NathanWalker commented on content/guide/core/fps-meter.md
> +### Stop measuring fps
```suggestion
### Stop measuring FPS
```

2023-07-28 15:05 UTC, NathanWalker commented on content/guide/core/fps-meter.md
> +To stop measuring the fps, remove the registered callback using its id and then call the module's [stop](#stop) method.
```suggestion
Remove the registered callback using its id and then call the [stop](#stop) method.
```

2023-07-28 15:06 UTC, merged