docs: ImageCache
NativeScript/docs pull request #58
Opened 2022-12-03 21:22 UTC by Ombuweb

2022-12-06 15:06 UTC, Ombuweb commented
When is the `ImageCache.downloadedEvent` triggered? The methods `enableDownload()` and `disableDownload()` don't seem to have any effect.

2023-06-11 03:22 UTC, ashutosh887 requested changes

2023-06-11 03:22 UTC, ashutosh887 commented on content/guide/ui/image-cache.md
> +To retrive an image from a remote server and cache it, use either the [push()](#push) or [enqueue()](#enqueue) method. These methods cache the image as `android.graphics.Bitamap`(Android) or `UIImage
It shold be `android.graphics.Bitmap`

2023-06-12 22:52 UTC, NathanWalker commented on content/guide/ui/image-cache.md
> +To retrive an image from a remote server and cache it, use either the [push()](#push) or [enqueue()](#enqueue) method. These methods cache the image as `android.graphics.Bitamap`(Android) or `UIImage
```suggestion
To retrieve an image from a remote server and cache it, use either the [push()](#push) or [enqueue()](#enqueue) method. These methods cache the image as `android.graphics.Bitmap` (Android) or `UIImage` (iOS) instance.
```

2023-06-12 22:54 UTC, NathanWalker commented on content/guide/ui/image-cache.md
> +if(cacheImage) notifyProperpyChange("imageSource", cachedImage)
```suggestion
// cachedImage for use
```

2023-06-14 12:47 UTC, ashutosh887 commented
Can we close this now? @NathanWalker

2023-06-14 15:36 UTC, NathanWalker commented on content/guide/ui/image-cache.md
> +The ImageCache class allows you to cache an image from an HTTP request.
```suggestion
ImageCache allows you to cache an image from an HTTP request.
```

2023-06-14 15:37 UTC, NathanWalker commented on content/guide/ui/image-cache.md
> +For consistency, you should use a single ImageCache instance
```suggestion
For consistency, you should use a single ImageCache instance throughout your app.
```

2023-06-14 15:37 UTC, NathanWalker commented on content/guide/ui/image-cache.md
> +throughout your data model.
```suggestion

```

2023-06-14 15:38 UTC, NathanWalker commented on content/guide/ui/image-cache.md
> +imageCache = new ImageCache()
```suggestion
const imageCache = new ImageCache()
```

2023-06-14 15:45 UTC, NathanWalker commented on content/guide/ui/image-cache.md
> +-  _Optional_: `complete` is a function to be called upon caching an image successfully.
```suggestion
-  _Optional_: `completed` is a function to be called upon caching an image successfully. 
```

2023-06-14 15:45 UTC, NathanWalker commented on content/guide/ui/image-cache.md
> +It removes the specified image from the cache.
```suggestion
Remove the specified image from the cache.
```

2023-06-14 15:46 UTC, NathanWalker commented on content/guide/ui/image-cache.md
> +It clears all the images from the cache.
```suggestion
Clears all the images from the cache.
```

2023-06-14 15:47 UTC, merged