docs: Navigation
NativeScript/docs pull request #59
Opened 2022-12-04 22:57 UTC by Ombuweb

2023-06-08 21:34 UTC, SeanKelly369 requested changes

2023-06-08 21:34 UTC, SeanKelly369 commented on content/guide/ui/navigation.md
> +To navigate to a page, first get the desired Frame instance. Then  for a simple navigation, call the instance's [navigate()](#navigate) method passing it the path of the page to navigate to.
How about ->

For page navigation, first obtain the desired Frame instance.
For a simple navigation, call the instance's navigate() method, with a string argument consisting of the desired path to navigate to.

2023-06-08 21:34 UTC, SeanKelly369 commented on content/guide/ui/navigation.md
> +The following are some of the ways to obtain an instance of the Frame class:
The following are some of the ways in which to obtain an instance of the Frame class:

2023-06-08 21:34 UTC, SeanKelly369 commented on content/guide/ui/navigation.md
> +- `navigate(entry: NavigationEntry)` is for a more customized navigation. It allows you to pass data to another page or set transition animation, etc.
It provides the ability  to pass data to another page, along with optionally setting a transition animation.

etc?  What are the other options?

2023-06-08 21:34 UTC, SeanKelly369 commented on content/guide/ui/navigation.md
> +Navigates back using the navigation hierarchy (if any). Updates the Frame stack as needed. This method will start from the topmost Frame and will recursively search for an instance that has the [canG
Navigates back using the navigation hierarchy, contained within a Frame stack where the top value is popped.

2023-06-09 16:57 UTC, NathanWalker commented on content/guide/ui/navigation.md
> +To navigate to a page, first get the desired Frame instance. Then  for a simple navigation, call the instance's [navigate()](#navigate) method passing it the path of the page to navigate to.
```suggestion
For page navigation, first obtain the desired Frame instance.
For a simple navigation, call the instance's navigate() method, with a string argument consisting of the desired path to navigate to.
```

2023-06-09 16:58 UTC, NathanWalker commented on content/guide/ui/navigation.md
> +The following are some of the ways to obtain an instance of the Frame class:
```suggestion
The following are some of the ways to obtain an instance of the Frame class:
```

2023-06-09 16:59 UTC, NathanWalker commented on content/guide/ui/navigation.md
> +Navigates back using the navigation hierarchy (if any). Updates the Frame stack as needed. This method will start from the topmost Frame and will recursively search for an instance that has the [canG
```suggestion
Navigates back using the navigation hierarchy, contained within a Frame stack where the top value is popped.
```

2023-06-11 12:36 UTC, SeanKelly369 approved these changes

2023-07-17 17:51 UTC, NathanWalker commented on content/guide/ui/navigation.md
> +To navigate to a page, first get the desired Frame instance. Then  for a simple navigation, call the instance's [navigate()](#navigate) method passing it the path of the page to navigate to.
```suggestion
For page navigation, first obtain the desired Frame instance.
For a simple navigation, call the instance's `navigate` method with a string argument consisting of the desired path to navigate to.
```

2023-07-17 17:52 UTC, NathanWalker commented on content/guide/ui/navigation.md
> +The following are some of the ways to obtain an instance of the Frame class:
```suggestion
The following are some of the ways in which to obtain an instance of the Frame class:
```

2023-07-17 17:55 UTC, NathanWalker commented on content/guide/ui/navigation.md
> +Navigates back using the navigation hierarchy (if any). Updates the Frame stack as needed. This method will start from the topmost Frame and will recursively search for an instance that has the [canG
```suggestion
Navigates back using the navigation stack contained within the topmost Frame and will recursively navigate back with each Frame instance which `canGoBack` returns true.
```

2023-07-17 18:56 UTC, NathanWalker approved these changes

2023-07-17 18:56 UTC, merged