docs: Property System
NativeScript/docs pull request #60
Opened 2022-12-06 15:48 UTC by Ombuweb

2023-05-22 16:51 UTC, NathanWalker commented on content/guide/property-system.md
> +NativeScript provides basic property system via the `Property` class, a simple wrapper around the [Object.defineProperty](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects
```suggestion
NativeScript provides a basic property system via the `Property` class, which is a simple wrapper around the [Object.defineProperty](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) with some additional callbacks like `valueChange`, `valueConverter` and `equalityComparer`.
```

2023-05-22 16:51 UTC, NathanWalker commented on content/guide/property-system.md
> +### Adding new a property to a View instace
```suggestion
### Adding a new property to a View instance
```

2023-05-22 16:53 UTC, NathanWalker commented on content/guide/property-system.md
> +To add a new property to a View class instance, instatiate the Property class with a [PropertyOptions](#propertyoptions-interface) object.
```suggestion
Add new properties by creating a new `Property` with desired [options](#propertyoptions-interface).
```

2023-05-22 16:54 UTC, NathanWalker commented on content/guide/property-system.md
> +Then register the property using the Property's instance [register()](#register) method:
```suggestion
Then register the property with the desired class:
```

2023-05-22 16:55 UTC, NathanWalker commented on content/guide/property-system.md
> +    name: "texty",
```suggestion
    name: "text",
```

2023-05-22 16:55 UTC, NathanWalker commented on content/guide/property-system.md
> +    this.nativeView.texty = value
```suggestion
    this.nativeView.text = value
```

2023-05-22 16:55 UTC, NathanWalker commented on content/guide/property-system.md
> +To apply the JS value to the exposed native view, call the [setNative]() method on the property instance.
```suggestion
To apply the JS value to the exposed native view, call the `setNative` method on the property instance.
```

2023-06-11 12:35 UTC, SeanKelly369 requested changes

2023-06-11 12:35 UTC, SeanKelly369 commented on content/guide/property-system.md
> +The property system in NativeScript is a way to expose a native property when you are exposing a native UI component.
The property system in NativeScript allows for the exposure of native properties when exposing a native UI component.

2023-06-11 12:35 UTC, SeanKelly369 commented on content/guide/property-system.md
> +NativeScript provides a basic property system via the `Property` class, which is a simple wrapper around the [Object.defineProperty](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Glo
Within NativeScript, the Property class serves as a fundamental property system, encompassing a straightforward wrapper around the [Object.defineProperty](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) function. This class also incorporates supplementary callbacks such as valueChange, valueConverter, and equalityComparer.

2023-06-11 12:35 UTC, SeanKelly369 commented on content/guide/property-system.md
> +For a complete real world example about exposing a native UI Component to NativeScript developers, and how the Property system is used, read the [How to create a NativeScript plugin that uses native
To gain a comprehensive understanding of how the Property system is employed in NativeScript to expose a native UI component, I recommend reading the informative article titled [How to create a NativeScript plugin that uses native iOS & Android views (Part 1) - Label Marquee!](https://blog.nativescript.org/create-a-custom-view-plugin-marquee-label/). This article provides a practical real-world example that demonstrates the process of developing a NativeScript plugin while utilizing native iOS and Android views.

2023-06-11 12:35 UTC, SeanKelly369 commented on content/guide/property-system.md
> +The name of the property to be used in a CSS rule.
The property name intended for utilization within a CSS rule.

2023-06-11 12:35 UTC, SeanKelly369 commented on content/guide/property-system.md
> +<!-- TODO: Add example -->
Don't forget to add an example

2023-06-11 12:35 UTC, SeanKelly369 commented on content/guide/property-system.md
> +Then when setting the property value, you call the `coerce()` method:
Subsequently, when assigning a value to the property, invoke the coerce() method.

2023-06-11 12:35 UTC, SeanKelly369 commented on content/guide/property-system.md
> +<!-- TODO: Add a proper explanation about when to create this property -->
TODO here

2023-06-11 12:35 UTC, SeanKelly369 commented on content/guide/property-system.md
> +To create a shorthand property, use the CssPropery class to define all the properties to be shortened. Then return the shorthand with the `getter()` method of the ShorthandProperty class.
Typo found.  `CssPropery` should be `CssProperty`

2023-06-11 12:35 UTC, SeanKelly369 commented on content/guide/property-system.md
> +Now any instance of the [Style](https://docs.nativescript.org/api-reference/classes/style) class will have `myOpacity` property and developers can set it in CSS as follows:
Subsequently, any instance of the...

2023-07-17 15:30 UTC, NathanWalker commented on content/guide/property-system.md
> +The property system in NativeScript is a way to expose a native property when you are exposing a native UI component.
```suggestion
The property system in NativeScript allows for the exposure of native platform properties to JavaScript components with certain guarantees built-in; for instance:
- it will set properties only after the native platform object is created
- it allows for property definitions with custom value converters
- it auto detects if property values change
- it can suspend updating of values when desired
- it can auto request layout updates when properties change when desired
```

2023-07-17 15:44 UTC, NathanWalker commented on content/guide/property-system.md
> +NativeScript provides a basic property system via the `Property` class, which is a simple wrapper around the [Object.defineProperty](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Glo
```suggestion
Within NativeScript, the Property class serves as a fundamental property system, encompassing a straightforward wrapper around the [Object.defineProperty](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) function. This class also incorporates supplementary callbacks such as valueChange, valueConverter, and equalityComparer.
```

2023-07-17 15:59 UTC, NathanWalker commented on content/guide/property-system.md
> +Within NativeScript, the Property class serves as a fundamental property system, encompassing a straightforward wrapper around the [Object.defineProperty](https://developer.mozilla.org/en/docs/Web/Ja
```suggestion
Within NativeScript, the Property class serves as a fundamental property system, encompassing a straightforward enhancement to the [Object.defineProperty](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) function. This class also incorporates supplementary callbacks such as valueChange, valueConverter, and equalityComparer.
```

2023-07-17 16:00 UTC, NathanWalker commented on content/guide/property-system.md
> +For a complete real world example about exposing a native UI Component to NativeScript developers, and how the Property system is used, read the [How to create a NativeScript plugin that uses native
```suggestion
To gain a comprehensive understanding of how the Property system is employed in NativeScript to expose a native UI component, I recommend reading the informative article titled [How to create a NativeScript plugin that uses native iOS & Android views (Part 1) - Label Marquee!](https://blog.nativescript.org/create-a-custom-view-plugin-marquee-label/). This article provides a practical real-world example that demonstrates the process of developing a NativeScript plugin while utilizing native iOS and Android views.
```

2023-07-17 16:23 UTC, NathanWalker commented on content/guide/property-system.md
> +Now any instance of the [Style](https://docs.nativescript.org/api-reference/classes/style) class will have `myOpacity` property and developers can set it in CSS as follows:
```suggestion
Subsequently, any instance of the [Style](https://docs.nativescript.org/api-reference/classes/style) class will have `myOpacity` property and developers can set it in CSS as follows:
```

2023-07-17 16:28 UTC, NathanWalker commented on content/guide/property-system.md
> +<!-- TODO: Add a proper explanation about when to create this property -->
```suggestion

```

2023-07-17 16:29 UTC, NathanWalker commented on content/guide/property-system.md
> +Then when setting the property value, you call the `coerce()` method:
```suggestion
Subsequently, when assigning a value to the property, invoke the `coerce()` method.
```

2023-07-17 17:28 UTC, NathanWalker commented on content/guide/property-system.md
> +To create a shorthand property, use the CssPropery class to define all the properties to be shortened. Then return the shorthand with the `getter()` method of the ShorthandProperty class.
```suggestion
To create a shorthand property, use the `CssProperty` class to define all the properties individually as normal. Then return the shorthand with the `getter()` method of the `ShorthandProperty` class.
```
Here's an example of how the margin shorthand is implemented:
```ts
const marginProperty = new ShorthandProperty<Style, string | CoreTypes.PercentLengthType>({
	name: 'margin',
	cssName: 'margin',
	getter: function (this: Style) {
		if (PercentLength.equals(this.marginTop, this.marginRight) && PercentLength.equals(this.marginTop, this.marginBottom) && PercentLength.equals(this.marginTop, this.marginLeft)) {
			return this.marginTop;
		}

		return `${PercentLength.convertToString(this.marginTop)} ${PercentLength.convertToString(this.marginRight)} ${PercentLength.convertToString(this.marginBottom)} ${PercentLength.convertToString(this.marginLeft)}`;
	},
	converter: convertToMargins,
});
marginProperty.register(Style);
```

2023-07-17 17:29 UTC, NathanWalker commented on content/guide/property-system.md
> +```
```suggestion

```

2023-07-17 17:31 UTC, NathanWalker commented on content/guide/property-system.md
> +The name of the property to be used in a CSS rule.
```suggestion
The property name intended for utilization within a CSS rule.
```

2023-07-17 17:36 UTC, NathanWalker commented on content/guide/property-system.md
> +<!-- TODO: Add example -->
```suggestion

```

2023-07-17 17:41 UTC, merged